### PR TITLE
add React to Templating

### PR DESCRIPTION
**Pull request by alexandref93**
Javascript Library for building User Interfaces

### CODE REVIEW

**Comment by moklick** [comment]
hehe.. putting react under templating is kind of funny. As you can see the big players (jquery,angular,backbone,ember, etc) are not the list. It's more a list of things I dont't want to forget ;)

**Comment by alexandref93** [comment]
okay :)

2015-02-25 8:03 GMT-03:00 moklick <notifications@github.com>:

> hehe.. putting react under templating is kind of funny. As you can see the
> big players (jquery,angular,backbone,ember, etc) are not the list. It's
> more a list of things I dont't want to forget ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moklick/frontend-stuff/pull/23#issuecomment-75942162>.
>



-- 
Carlos A. Fuechter
@alexandref93 <http://twitter.com/#!/alexandref93>

**Comment by moklick** [comment]
I really like working with react. Maybe a list with good react components/helper whatever would make sense.

**Comment by alexandref93** [comment]
As a new topic on this project? Or other project only react
components/helper?

2015-02-25 10:08 GMT-03:00 moklick <notifications@github.com>:

> I really like working with react. Maybe a list with good react
> components/helper whatever would make sense.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moklick/frontend-stuff/pull/23#issuecomment-75956552>.
>



-- 
Carlos A. Fuechter
@alexandref93 <http://twitter.com/#!/alexandref93>

**Comment by moklick** [comment]
A new repo only with react stuff would make sense.. There is a really [big list](https://github.com/enaqx/awesome-react) but in my view it's too generic.. It's just a list with every react lib that is out there but not a list with handpicked stuff that is used in production

**Comment by alexandref93** [comment]
Cool, like this create the project, I post link this.

2015-02-25 10:15 GMT-03:00 moklick <notifications@github.com>:

> A new repo only with react stuff would make sense.. There is a really big
> list <https://github.com/enaqx/awesome-react> but in my view it's too
> generic.. It's just a list with every react lib that is out there but not a
> list with handpicked stuff that is used in production
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moklick/frontend-stuff/pull/23#issuecomment-75957420>.
>



-- 
Carlos A. Fuechter
@alexandref93 <http://twitter.com/#!/alexandref93>

**Comment by moklick** [comment]
so you are going to create list?

**Comment by alexandref93** [comment]
when I create the list, I post the link here**

2015-02-25 10:20 GMT-03:00 moklick <notifications@github.com>:

> so you are going to create list?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moklick/frontend-stuff/pull/23#issuecomment-75958041>.
>



-- 
Carlos A. Fuechter
@alexandref93 <http://twitter.com/#!/alexandref93>

**Comment by moklick** [comment]
awesome :)

**Comment by alexandref93** [comment]
hey moklick, you have some contact to exchange some ideas?

**Pull request closed without merging**
