### PR TITLE
Add ThreeWords to General section

### PR DESCRIPTION
**Pull request by albyr**

### CODE REVIEW

**Comment by moklick** [comment]
Sorry I don't get it. What is the use case for a front end library?

**Comment by albyr** [comment]
Say you have a website with thousands of pages, and your users occasionally need to convey the URLs for those pages without copying-and-pasting a link. This makes doing that easier for users.

From the README:
> http://www.example.com/3715986347 becomes http://www.example.com/SovietLaserBasket.
> http://www.example.com/3751968347 becomes http://www.example.com/SplitVolumeGlass.

**Comment by SeanHub** [comment]
I can't see a way of getting the ID back from the words, how is a server supposed to map the generated URL to a real URL? As far as I can see it just spits out 3 words when given a large number.

**Comment by moklick** [comment]
I saw the example with the URLs in the readme, but that is nothing you would do in the frontend.

**Pull request closed without merging**
