### PR TITLE
Added Caramel

### PR DESCRIPTION
**Pull request by kurisubrooks**
Requesting the addition of Caramel.
(github.com/kurisubrooks/caramel)

### CODE REVIEW

**Comment by moklick** [comment]
Seems nice but there is no package.json nor a bower.json. How should we use this?

**Comment by kurisubrooks** [comment]
It's simply just a CSS Framework. Think of it like Bootstrap.

**Comment by kurisubrooks** [comment]
I'll look into Bower.

**Comment by moklick** [comment]
Ok. If you want people to use your framework you have to make it as simple as possible to integrate it. 
with bower for example I could install it via `bower install caramel --save` with NPM via `npm install caramel --save`.

**Comment by kurisubrooks** [comment]
Registered it to their directory, 'caramel'
I'm looking into npm now.

Also, if people wish to use the latest of the framework, they can hook into the archives on our website. Up to them how to use it though.

**Comment by kurisubrooks** [comment]
As it's a CSS Framework, I think i'll leave it off NPM. It seems mostly for Node modules.

**Comment by moklick** [comment]
yep. bower is fine for that kind of framework.

**Comment by kurisubrooks** [comment]
Is there anything else?

**Comment by moklick** [comment]
Also a link to github or at least a "how to use it" section on http://caramel.ga/ would be nice. There is only one link at the bottom of the page and that one doesn't work.

**Comment by kurisubrooks** [comment]
I'm still working on the actual, proper website. Currently it's just the documentation up right now. I'll let you know when it's done :)

**Comment by kurisubrooks** [comment]
Our Website's done, uploaded, and ready to go!

**Comment by moklick** [comment]
ok thanks.

**Comment by kurisubrooks** [comment]
Thanks so much!

**Pull request merged**
